apiVersion: v1
kind: Pod
metadata:
  name: fleetman-webapp
  labels:
    app: fleetman-webapp
    release: "0"
spec:
  containers:
  - name: fleetman-webapp
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0

---
apiVersion: v1
kind: Pod
metadata:
  name: fleetman-webapp-release-0-5
  labels:
    app: fleetman-webapp
    release: 0-5
spec:
  containers:
  - name: fleetman-webapp
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5

---
apiVersion: v1
kind: Pod
metadata:
  name: fleetman-queue
  labels:
    app: fleetman-queue
spec:
  containers:
  - name: fleetman-queue
    image: richardchesterwood/k8s-fleetman-queue:release1
