apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  # template is like pod template. and no longer needed pod name replicaset auto assigns names
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: fleetman-webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0

---
apiVersion: v1
kind: Pod
metadata:
  name: fleetman-queue
  labels:
    app: fleetman-queue
spec:
  containers:
  - name: fleetman-queue
    image: richardchesterwood/k8s-fleetman-queue:release1
