apiVersion: v1
kind: Service
metadata:
  name: kubernetes-webapp
spec:
  # filter pods by selector
  # this service becomes a network endpoint for other services and external users to connect to (browser)
  selector:
    app: webapp

  ports:
    # name is just documenting that we're expecging http traffice
    - name: http
      port: 80
      # for services of type NodePort, can specify port > 30000 to expose
      # for live you will instead use type load balancer which can expose any port
      nodePort: 30001
      # targetPort defaults to value of port
      targetPort: 80

  type: NodePort
